# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'child.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChildForm(object):
    def setupUi(self, ChildForm):
        ChildForm.setObjectName("ChildForm")
        ChildForm.resize(400, 300)
        self.textEdit = QtWidgets.QTextEdit(ChildForm)
        self.textEdit.setGeometry(QtCore.QRect(70, 60, 251, 151))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(ChildForm)
        QtCore.QMetaObject.connectSlotsByName(ChildForm)

    def retranslateUi(self, ChildForm):
        _translate = QtCore.QCoreApplication.translate
        ChildForm.setWindowTitle(_translate("ChildForm", "child_Form"))
        self.textEdit.setHtml(_translate("ChildForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">我是子窗口</p></body></html>"))
